---
apiVersion: v1
kind: Service
metadata:
  name: boot-node-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: boot-node
spec:
  type: ClusterIP
  ports:
    - port: 5678
      protocol: TCP
      targetPort: 5678
      name: port-5678
  selector:
    app: boot-node
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: boot-node
  name: boot-node
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: boot-node
  template:
    metadata:
      labels:
        app: boot-node
    spec:
      containers:
      - name: boot-node
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["make", "start-boot-node"]
        ports:
        - containerPort: 5678
          name: port-5678
