version: '3.5'

x-base:
  &default-base
  build:
    context: .
    dockerfile: Dockerfile
  image: ssvnode:latest
  command: make BUILD_PATH=/go/bin/ssvnode start-node
  networks:
    - bloxapp-docker
  restart: always

x-base-dev:
  &default-dev
  << : *default-base
  image: ssvnode-debug:latest
  build:
    context: .
    dockerfile: dev.Dockerfile
  command:  air
  security_opt:
    - "seccomp:unconfined"
  cap_add:
    - SYS_PTRACE
  volumes:
    - ./:/go/src/github.com/bloxapp/ssv


services:
  ssv-node-1:
    <<: *default-base
    container_name: ssv-node-1
    environment:
      DOCKER_COMPOSE: "true"
      NODE_ID: 1
      SSV_PRIVATE_KEY: ${SSV_NODE_1}
      PUBKEY_NODE_2: ${SSV_NODE_PUB_KEY_2}
      PUBKEY_NODE_3: ${SSV_NODE_PUB_KEY_3}
      PUBKEY_NODE_4: ${SSV_NODE_PUB_KEY_4}

  ssv-node-2:
    <<: *default-base
    container_name: ssv-node-2
    environment:
      DOCKER_COMPOSE: "true"
      NODE_ID: 2
      SSV_PRIVATE_KEY: ${SSV_NODE_2}
      PUBKEY_NODE_1: ${SSV_NODE_PUB_KEY_1}
      PUBKEY_NODE_3: ${SSV_NODE_PUB_KEY_3}
      PUBKEY_NODE_4: ${SSV_NODE_PUB_KEY_4}

  ssv-node-3:
    <<: *default-base
    container_name: ssv-node-3
    environment:
      DOCKER_COMPOSE: "true"
      NODE_ID: 3
      SSV_PRIVATE_KEY: ${SSV_NODE_3}
      PUBKEY_NODE_1: ${SSV_NODE_PUB_KEY_1}
      PUBKEY_NODE_2: ${SSV_NODE_PUB_KEY_2}
      PUBKEY_NODE_4: ${SSV_NODE_PUB_KEY_4}

  ssv-node-4:
    <<: *default-base
    container_name: ssv-node-4
    environment:
      DOCKER_COMPOSE: "true"
      NODE_ID: 4
      SSV_PRIVATE_KEY: ${SSV_NODE_4}
      PUBKEY_NODE_1: ${SSV_NODE_PUB_KEY_1}
      PUBKEY_NODE_2: ${SSV_NODE_PUB_KEY_2}
      PUBKEY_NODE_3: ${SSV_NODE_PUB_KEY_3}


  ssv-node-1-dev:
    << : *default-dev
    container_name: ssv-node-1-dev
    ports:
      - 40005:40005
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DOCKER_COMPOSE: "true"
      NODE_ID: 1
      SSV_PRIVATE_KEY: ${SSV_NODE_1}
      PUBKEY_NODE_2: ${SSV_NODE_PUB_KEY_2}
      PUBKEY_NODE_3: ${SSV_NODE_PUB_KEY_3}
      PUBKEY_NODE_4: ${SSV_NODE_PUB_KEY_4}
      DEBUG_PORT: 40005

  ssv-node-2-dev:
    << : *default-dev
    container_name: ssv-node-2-dev
    ports:
      - 40006:40006
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DOCKER_COMPOSE: "true"
      NODE_ID: 2
      SSV_PRIVATE_KEY: ${SSV_NODE_2}
      PUBKEY_NODE_1: ${SSV_NODE_PUB_KEY_1}
      PUBKEY_NODE_3: ${SSV_NODE_PUB_KEY_3}
      PUBKEY_NODE_4: ${SSV_NODE_PUB_KEY_4}
      DEBUG_PORT: 40006

  ssv-node-3-dev:
    << : *default-dev
    container_name: ssv-node-3-dev
    ports:
      - 40007:40007
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DOCKER_COMPOSE: "true"
      NODE_ID: 3
      SSV_PRIVATE_KEY: ${SSV_NODE_3}
      PUBKEY_NODE_1: ${SSV_NODE_PUB_KEY_1}
      PUBKEY_NODE_2: ${SSV_NODE_PUB_KEY_2}
      PUBKEY_NODE_4: ${SSV_NODE_PUB_KEY_4}
      DEBUG_PORT: 40007

  ssv-node-4-dev:
    << : *default-dev
    container_name: ssv-node-4-dev
    ports:
      - 40008:40008
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DOCKER_COMPOSE: "true"
      NODE_ID: 4
      SSV_PRIVATE_KEY: ${SSV_NODE_4}
      PUBKEY_NODE_1: ${SSV_NODE_PUB_KEY_1}
      PUBKEY_NODE_2: ${SSV_NODE_PUB_KEY_2}
      PUBKEY_NODE_3: ${SSV_NODE_PUB_KEY_3}
      DEBUG_PORT: 40008

networks:
  bloxapp-docker:
    driver: bridge
    name: bloxapp-docker