version: '3.5'

services:
  ssv-node-1:
    build:
      context: .
      dockerfile: Dockerfile
    command: start-node --node-id 1 --leader-id 1 --private-key ${SSN_NODE_1} --validator-key ${VALIDATOR_PUBLIC_KEY} --beacon-node-addr ${BEACON_NODE_ADDR} --network ${NETWORK}
    environment:
      DOCKER_COMPOSE: "true"
    networks:
      - bloxapp-docker
    restart: always

  ssv-node-2:
    build:
      context: .
      dockerfile: Dockerfile
    command: start-node --node-id 2 --leader-id 1 --private-key ${SSN_NODE_2} --validator-key ${VALIDATOR_PUBLIC_KEY} --beacon-node-addr ${BEACON_NODE_ADDR} --network ${NETWORK}
    environment:
      DOCKER_COMPOSE: "true"
    networks:
      - bloxapp-docker
    restart: always

  ssv-node-3:
    build:
      context: .
      dockerfile: Dockerfile
    command: start-node --node-id 3 --leader-id 1 --private-key ${SSN_NODE_2} --validator-key ${VALIDATOR_PUBLIC_KEY} --beacon-node-addr ${BEACON_NODE_ADDR} --network ${NETWORK}
    environment:
      DOCKER_COMPOSE: "true"
    networks:
      - bloxapp-docker
    restart: always

networks:
  bloxapp-docker:
    driver: bridge
    name: bloxapp-docker