global:
  LogLevel: debug

db:
  Path: ./data/db

eth2:
### replace with your beacon node address
  BeaconNodeAddr: eth2-lh-prater-5052-ext.stage.bloxinfra.com:80
  Network: prater

eth1:
### replace with your eth1 node address
  ETH1Addr: example.url

p2p:
### replace with your ip and ports
### otherwise, the default ports (TCP 13001, UDP 12001) are used
#  HostAddress:
#  TcpPort:
#  UdpPort:
### mdns for local network setup
#  DiscoveryType: mdns

ssv:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

### replace with your operator key
### NOTES:
###  - required for operators
###  - optional for exporters
OperatorPrivateKey:
