global:
  LogLevel: debug

db:
  Path: ./data/db

eth2:
  BeaconNodeAddr: eth2-lh-prater-5052.stage.bloxinfra.com:80
  Network: prater

eth1:
  # ETH1 node WebSocket address
  ETH1Addr: ws://eth1-ws-ext.stage.bloxinfra.com/ws

p2p:
  # replace with your ip
#  HostAddress: example.ip
#  TcpPort:
#  UdpPort:
  Bootnodes:
  HostAddress: 127.0.0.1

ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

OperatorPrivateKey:

bootnode:
  ExternalIP:
  PrivateKey:
