global:
  LogLevel: info

db:
  Path: ./data/db
  Type: badger-db

eth2:
  Network:
#  BeaconNodeAddr: prater-4000-ext.stage.bloxinfra.com:80
#  BeaconNodeAddr: prater-4000:stage:bloxinfra:com:80
  BeaconNodeAddr: http://eth2-lh-prater-5052.stage.bloxinfra.com


ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

OperatorPrivateKey:
eth1:
  ETH1Addr: ws://eth1-ws.stage.bloxinfra.com/ws
p2p:
  HostAddress: example.ip
  TcpPort:
  UdpPort:

bootnode:
  ExternalIP:
  PrivateKey:
