global:
  LogLevel: info

db:
  Path: ./data/db

p2p:
  # replace with your ip
  HostAddress: example.ip
  TcpPort:
  UdpPort:
  # mdns for local network setup
  DiscoveryType: mdns

ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

OperatorPrivateKey:

bootnode:
  ExternalIP:
  PrivateKey:
