name: Lint

on: push

jobs:
  release:
￼   runs-on: ${{ matrix.os }}

￼   strategy:
￼     matrix:
￼       os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/checkout@v2

      - name: Set up Go
￼       if: ${{ startsWith(github.ref, 'refs/tags/v') }}
￼       uses: actions/setup-go@v2
￼       with:
￼         go-version: 1.16

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make
       
      - name: Run lint-prepare 
        run: make lint-prepare

      - name: Run make lint
        run: make lint
